/*

Custom exception handler example

Class:              Framework_NoHandlerException
Date:               12/20/2013
Version:            1
Last Updated:       12/20/2013
    * 	Stubbed for sample

While this could be used for additional logging in the package or clients
instance, its only purpose now is to throw an error when an trigger handler
is not defined in the framework and the trigger event is called.
////////////////////////////////////////////////////////////////////////////////
*/

global class Framework_NoHandlerException extends Exception {
	
	// -------- Constants --------
	// None
	
	// -------- Constructor --------
    // Parent
    
    // -------- Variables --------
	// None
	
	// -------- Properties --------
	// None
	
	// -------- Methods --------
	// None
	
	// -------- Internal Classes --------
	// None
}